version: '3'

services:

  web:
    build: ./docker/web
    volumes:
      - ./:/var/app
    ports:
      - '3000:3000'
    environment:
      - NEXT_TELEMETRY_DEBUG=1 # data will be printed but not sent to nextjs.org